using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace CloudServicePackageModule.Schema
{
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     This code was generated by a tool.
    //     Runtime Version:4.0.30319.42000
    //
    //     Changes to this file may cause incorrect behavior and will be lost if
    //     the code is regenerated.
    // </auto-generated>
    //------------------------------------------------------------------------------

    using System.Xml.Serialization;

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition", IsNullable = false)]
    public partial class RoleModule
    {

        private Startup startupField;

        private RuntimeForRoleModule runtimeField;

        private ConfigurationSetting[] configurationSettingsField;

        private Endpoints endpointsField;

        private LocalResources localResourcesField;

        private Certificate[] certificatesField;

        private Sites sitesField;

        private string namespaceField;

        /// <remarks/>
        public Startup Startup
        {
            get
            {
                return this.startupField;
            }
            set
            {
                this.startupField = value;
            }
        }

        /// <remarks/>
        public RuntimeForRoleModule Runtime
        {
            get
            {
                return this.runtimeField;
            }
            set
            {
                this.runtimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Setting", IsNullable = false)]
        public ConfigurationSetting[] ConfigurationSettings
        {
            get
            {
                return this.configurationSettingsField;
            }
            set
            {
                this.configurationSettingsField = value;
            }
        }

        /// <remarks/>
        public Endpoints Endpoints
        {
            get
            {
                return this.endpointsField;
            }
            set
            {
                this.endpointsField = value;
            }
        }

        /// <remarks/>
        public LocalResources LocalResources
        {
            get
            {
                return this.localResourcesField;
            }
            set
            {
                this.localResourcesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public Certificate[] Certificates
        {
            get
            {
                return this.certificatesField;
            }
            set
            {
                this.certificatesField = value;
            }
        }

        /// <remarks/>
        public Sites Sites
        {
            get
            {
                return this.sitesField;
            }
            set
            {
                this.sitesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("namespace")]
        public string Namespace
        {
            get
            {
                return this.namespaceField;
            }
            set
            {
                this.namespaceField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition", IsNullable = true)]
    public partial class Startup
    {

        private Task[] taskField;

        private int priorityField;

        public Startup()
        {
            this.priorityField = 0;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Task")]
        public Task[] Task
        {
            get
            {
                return this.taskField;
            }
            set
            {
                this.taskField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("priority")]
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int Priority
        {
            get
            {
                return this.priorityField;
            }
            set
            {
                this.priorityField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition", IsNullable = true)]
    public partial class Task
    {

        private Variable[] environmentField;

        private string commandLineField;

        private ExecutionContext executionContextField;

        private TaskType taskTypeField;

        public Task()
        {
            this.executionContextField = ExecutionContext.limited;
            this.taskTypeField = TaskType.simple;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public Variable[] Environment
        {
            get
            {
                return this.environmentField;
            }
            set
            {
                this.environmentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("commandLine")]
        public string CommandLine
        {
            get
            {
                return this.commandLineField;
            }
            set
            {
                this.commandLineField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("executionContext")]
        [System.ComponentModel.DefaultValueAttribute(ExecutionContext.limited)]
        public ExecutionContext ExecutionContext
        {
            get
            {
                return this.executionContextField;
            }
            set
            {
                this.executionContextField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("taskType")]
        [System.ComponentModel.DefaultValueAttribute(TaskType.simple)]
        public TaskType TaskType
        {
            get
            {
                return this.taskTypeField;
            }
            set
            {
                this.taskTypeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition", IsNullable = true)]
    public partial class Variable
    {

        private RoleInstanceValueElement roleInstanceValueField;

        private string nameField;

        private string valueField;

        /// <remarks/>
        public RoleInstanceValueElement RoleInstanceValue
        {
            get
            {
                return this.roleInstanceValueField;
            }
            set
            {
                this.roleInstanceValueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("name")]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("value")]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition", IsNullable = true)]
    public partial class RoleInstanceValueElement
    {

        private string xpathField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("xpath")]
        public string Xpath
        {
            get
            {
                return this.xpathField;
            }
            set
            {
                this.xpathField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition", IsNullable = true)]
    public partial class Certificate
    {

        private string nameField;

        private StoreLocation storeLocationField;

        private string storeNameField;

        private PermissionLevel permissionLevelField;

        public Certificate()
        {
            this.permissionLevelField = PermissionLevel.limitedOrElevated;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("name")]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("storeLocation")]
        public StoreLocation StoreLocation
        {
            get
            {
                return this.storeLocationField;
            }
            set
            {
                this.storeLocationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("storeName")]
        public string StoreName
        {
            get
            {
                return this.storeNameField;
            }
            set
            {
                this.storeNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("permissionLevel")]
        [System.ComponentModel.DefaultValueAttribute(PermissionLevel.limitedOrElevated)]
        public PermissionLevel PermissionLevel
        {
            get
            {
                return this.permissionLevelField;
            }
            set
            {
                this.permissionLevelField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition", IsNullable = false)]
    public enum StoreLocation
    {

        /// <remarks/>
        CurrentUser,

        /// <remarks/>
        LocalMachine,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition", IsNullable = false)]
    public enum PermissionLevel
    {

        /// <remarks/>
        limitedOrElevated,

        /// <remarks/>
        elevated,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition", IsNullable = true)]
    public partial class Binding
    {

        private string nameField;

        private string endpointNameField;

        private string hostHeaderField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("name")]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("endpointName")]
        public string EndpointName
        {
            get
            {
                return this.endpointNameField;
            }
            set
            {
                this.endpointNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("hostHeader")]
        public string HostHeader
        {
            get
            {
                return this.hostHeaderField;
            }
            set
            {
                this.hostHeaderField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition", IsNullable = true)]
    public partial class LoadBalancerProbe
    {

        private string nameField;

        private ProbeProtocol protocolField;

        private int portField;

        private bool portFieldSpecified;

        private string pathField;

        private int intervalInSecondsField;

        private int timeoutInSecondsField;

        public LoadBalancerProbe()
        {
            this.intervalInSecondsField = 15;
            this.timeoutInSecondsField = 31;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("name")]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("protocol")]
        public ProbeProtocol Protocol
        {
            get
            {
                return this.protocolField;
            }
            set
            {
                this.protocolField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("port")]
        public int Port
        {
            get
            {
                return this.portField;
            }
            set
            {
                this.portField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PortSpecified
        {
            get
            {
                return this.portFieldSpecified;
            }
            set
            {
                this.portFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("path")]
        public string Path
        {
            get
            {
                return this.pathField;
            }
            set
            {
                this.pathField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("intervalInSeconds")]
        [System.ComponentModel.DefaultValueAttribute(15)]
        public int IntervalInSeconds
        {
            get
            {
                return this.intervalInSecondsField;
            }
            set
            {
                this.intervalInSecondsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("timeoutInSeconds")]
        [System.ComponentModel.DefaultValueAttribute(31)]
        public int TimeoutInSeconds
        {
            get
            {
                return this.timeoutInSecondsField;
            }
            set
            {
                this.timeoutInSecondsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition", IsNullable = false)]
    public enum ProbeProtocol
    {

        /// <remarks/>
        http,

        /// <remarks/>
        tcp,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition", IsNullable = true)]
    public partial class Import
    {

        private string moduleNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("moduleName")]
        public string ModuleName
        {
            get
            {
                return this.moduleNameField;
            }
            set
            {
                this.moduleNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition", IsNullable = true)]
    public partial class OnlyAllowTrafficTo
    {

        private Destinations destinationsField;

        private object itemField;

        /// <remarks/>
        public Destinations Destinations
        {
            get
            {
                return this.destinationsField;
            }
            set
            {
                this.destinationsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AllowAllTraffic", typeof(AllowAllTraffic))]
        [System.Xml.Serialization.XmlElementAttribute("WhenSource", typeof(WhenSource))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition", IsNullable = true)]
    public partial class Destinations
    {

        private RoleEndpoint[] roleEndpointField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RoleEndpoint")]
        public RoleEndpoint[] RoleEndpoint
        {
            get
            {
                return this.roleEndpointField;
            }
            set
            {
                this.roleEndpointField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition", IsNullable = true)]
    public partial class RoleEndpoint
    {

        private string roleNameField;

        private string endpointNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("roleName")]
        public string RoleName
        {
            get
            {
                return this.roleNameField;
            }
            set
            {
                this.roleNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("endpointName")]
        public string EndpointName
        {
            get
            {
                return this.endpointNameField;
            }
            set
            {
                this.endpointNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition", IsNullable = true)]
    public partial class AllowAllTraffic
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition", IsNullable = true)]
    public partial class WhenSource
    {

        private FromRole[] fromRoleField;

        private MatchMode matchesField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FromRole")]
        public FromRole[] FromRole
        {
            get
            {
                return this.fromRoleField;
            }
            set
            {
                this.fromRoleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("matches")]
        public MatchMode Matches
        {
            get
            {
                return this.matchesField;
            }
            set
            {
                this.matchesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition", IsNullable = true)]
    public partial class FromRole
    {

        private string roleNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("roleName")]
        public string RoleName
        {
            get
            {
                return this.roleNameField;
            }
            set
            {
                this.roleNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition", IsNullable = false)]
    public enum MatchMode
    {

        /// <remarks/>
        AnyRule,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition", IsNullable = false)]
    public enum ExecutionContext
    {

        /// <remarks/>
        limited,

        /// <remarks/>
        elevated,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition", IsNullable = false)]
    public enum TaskType
    {

        /// <remarks/>
        simple,

        /// <remarks/>
        foreground,

        /// <remarks/>
        background,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition", IsNullable = true)]
    public partial class RuntimeForRoleModule : Runtime
    {
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RuntimeForRoleModule))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WebRuntime))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WorkerRuntime))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition", IsNullable = true)]
    public partial class Runtime
    {

        private Variable[] environmentField;

        private ExecutionContext executionContextField;

        public Runtime()
        {
            this.executionContextField = ExecutionContext.limited;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public Variable[] Environment
        {
            get
            {
                return this.environmentField;
            }
            set
            {
                this.environmentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("executionContext")]
        [System.ComponentModel.DefaultValueAttribute(ExecutionContext.limited)]
        public ExecutionContext ExecutionContext
        {
            get
            {
                return this.executionContextField;
            }
            set
            {
                this.executionContextField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition", IsNullable = true)]
    public partial class ConfigurationSetting
    {

        private string nameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("name")]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition", IsNullable = true)]
    public partial class Endpoints
    {

        private InputEndpoint[] inputEndpointField;

        private InternalEndpoint[] internalEndpointField;

        private InstanceInputEndpointElement[] instanceInputEndpointField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InputEndpoint")]
        public InputEndpoint[] InputEndpoint
        {
            get
            {
                return this.inputEndpointField;
            }
            set
            {
                this.inputEndpointField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InternalEndpoint")]
        public InternalEndpoint[] InternalEndpoint
        {
            get
            {
                return this.internalEndpointField;
            }
            set
            {
                this.internalEndpointField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InstanceInputEndpoint")]
        public InstanceInputEndpointElement[] InstanceInputEndpoint
        {
            get
            {
                return this.instanceInputEndpointField;
            }
            set
            {
                this.instanceInputEndpointField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition", IsNullable = true)]
    public partial class InputEndpoint
    {

        private string nameField;

        private Protocol protocolField;

        private int portField;

        private string certificateField;

        private string localPortField;

        private bool ignoreRoleInstanceStatusField;

        private string loadBalancerProbeField;

        private string loadBalancerField;

        private int idleTimeoutInMinutesField;

        private bool idleTimeoutInMinutesFieldSpecified;

        private DistributionType loadBalancerDistributionField;

        private bool loadBalancerDistributionFieldSpecified;

        public InputEndpoint()
        {
            this.ignoreRoleInstanceStatusField = false;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("name")]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("protocol")]
        public Protocol Protocol
        {
            get
            {
                return this.protocolField;
            }
            set
            {
                this.protocolField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("port")]
        public int Port
        {
            get
            {
                return this.portField;
            }
            set
            {
                this.portField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("certificate")]
        public string Certificate
        {
            get
            {
                return this.certificateField;
            }
            set
            {
                this.certificateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("localPort")]
        public string LocalPort
        {
            get
            {
                return this.localPortField;
            }
            set
            {
                this.localPortField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("ignoreRoleInstanceStatus")]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool IgnoreRoleInstanceStatus
        {
            get
            {
                return this.ignoreRoleInstanceStatusField;
            }
            set
            {
                this.ignoreRoleInstanceStatusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("loadBalancerProbe")]
        public string LoadBalancerProbe
        {
            get
            {
                return this.loadBalancerProbeField;
            }
            set
            {
                this.loadBalancerProbeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("loadBalancer")]
        public string LoadBalancer
        {
            get
            {
                return this.loadBalancerField;
            }
            set
            {
                this.loadBalancerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("idleTimeoutInMinutes")]
        public int IdleTimeoutInMinutes
        {
            get
            {
                return this.idleTimeoutInMinutesField;
            }
            set
            {
                this.idleTimeoutInMinutesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdleTimeoutInMinutesSpecified
        {
            get
            {
                return this.idleTimeoutInMinutesFieldSpecified;
            }
            set
            {
                this.idleTimeoutInMinutesFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("loadBalancerDistribution")]
        public DistributionType LoadBalancerDistribution
        {
            get
            {
                return this.loadBalancerDistributionField;
            }
            set
            {
                this.loadBalancerDistributionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LoadBalancerDistributionSpecified
        {
            get
            {
                return this.loadBalancerDistributionFieldSpecified;
            }
            set
            {
                this.loadBalancerDistributionFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition", IsNullable = false)]
    public enum Protocol
    {

        /// <remarks/>
        http,

        /// <remarks/>
        https,

        /// <remarks/>
        tcp,

        /// <remarks/>
        udp,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition", IsNullable = false)]
    public enum DistributionType
    {

        /// <remarks/>
        sourceIP,

        /// <remarks/>
        sourceIPProtocol,

        /// <remarks/>
        none,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition", IsNullable = true)]
    public partial class InternalEndpoint
    {

        private PortType[] fixedPortField;

        private PortRange[] fixedPortRangeField;

        private string nameField;

        private string portField;

        private InternalProtocol protocolField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FixedPort")]
        public PortType[] FixedPort
        {
            get
            {
                return this.fixedPortField;
            }
            set
            {
                this.fixedPortField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FixedPortRange")]
        public PortRange[] FixedPortRange
        {
            get
            {
                return this.fixedPortRangeField;
            }
            set
            {
                this.fixedPortRangeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("name")]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("port")]
        public string Port
        {
            get
            {
                return this.portField;
            }
            set
            {
                this.portField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("protocol")]
        public InternalProtocol Protocol
        {
            get
            {
                return this.protocolField;
            }
            set
            {
                this.protocolField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition", IsNullable = true)]
    public partial class PortType
    {

        private int portField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("port")]
        public int Port
        {
            get
            {
                return this.portField;
            }
            set
            {
                this.portField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition", IsNullable = true)]
    public partial class PortRange
    {

        private int minField;

        private int maxField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("min")]
        public int Min
        {
            get
            {
                return this.minField;
            }
            set
            {
                this.minField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("max")]
        public int Max
        {
            get
            {
                return this.maxField;
            }
            set
            {
                this.maxField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition", IsNullable = false)]
    public enum InternalProtocol
    {

        /// <remarks/>
        http,

        /// <remarks/>
        tcp,

        /// <remarks/>
        udp,

        /// <remarks/>
        any,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition", IsNullable = true)]
    public partial class InstanceInputEndpointElement
    {

        private AllocatePublicPortFromElement allocatePublicPortFromField;

        private string nameField;

        private int localPortField;

        private TransportProtocol protocolField;

        private int idleTimeoutInMinutesField;

        private bool idleTimeoutInMinutesFieldSpecified;

        /// <remarks/>
        public AllocatePublicPortFromElement AllocatePublicPortFrom
        {
            get
            {
                return this.allocatePublicPortFromField;
            }
            set
            {
                this.allocatePublicPortFromField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("name")]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("localPort")]
        public int LocalPort
        {
            get
            {
                return this.localPortField;
            }
            set
            {
                this.localPortField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("protocol")]
        public TransportProtocol Protocol
        {
            get
            {
                return this.protocolField;
            }
            set
            {
                this.protocolField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("idleTimeoutInMinutes")]
        public int IdleTimeoutInMinutes
        {
            get
            {
                return this.idleTimeoutInMinutesField;
            }
            set
            {
                this.idleTimeoutInMinutesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdleTimeoutInMinutesSpecified
        {
            get
            {
                return this.idleTimeoutInMinutesFieldSpecified;
            }
            set
            {
                this.idleTimeoutInMinutesFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition", IsNullable = true)]
    public partial class AllocatePublicPortFromElement
    {

        private PortRange fixedPortRangeField;

        /// <remarks/>
        public PortRange FixedPortRange
        {
            get
            {
                return this.fixedPortRangeField;
            }
            set
            {
                this.fixedPortRangeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition", IsNullable = false)]
    public enum TransportProtocol
    {

        /// <remarks/>
        udp,

        /// <remarks/>
        tcp,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition", IsNullable = true)]
    public partial class LocalResources
    {

        private LocalStore[] localStorageField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LocalStorage")]
        public LocalStore[] LocalStorage
        {
            get
            {
                return this.localStorageField;
            }
            set
            {
                this.localStorageField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition", IsNullable = true)]
    public partial class LocalStore
    {

        private string nameField;

        private int sizeInMBField;

        private bool cleanOnRoleRecycleField;

        public LocalStore()
        {
            this.sizeInMBField = 1000;
            this.cleanOnRoleRecycleField = true;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("name")]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("sizeInMB")]
        [System.ComponentModel.DefaultValueAttribute(1000)]
        public int SizeInMB
        {
            get
            {
                return this.sizeInMBField;
            }
            set
            {
                this.sizeInMBField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("cleanOnRoleRecycle")]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool CleanOnRoleRecycle
        {
            get
            {
                return this.cleanOnRoleRecycleField;
            }
            set
            {
                this.cleanOnRoleRecycleField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition", IsNullable = true)]
    public partial class Sites
    {

        private Site[] siteField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Site")]
        public Site[] Site
        {
            get
            {
                return this.siteField;
            }
            set
            {
                this.siteField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition", IsNullable = true)]
    public partial class Site : VirtualDirectory
    {

        private Binding[] bindingsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public Binding[] Bindings
        {
            get
            {
                return this.bindingsField;
            }
            set
            {
                this.bindingsField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(VirtualApplication))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Site))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition", IsNullable = true)]
    public partial class VirtualDirectory
    {

        private VirtualDirectory[] itemsField;

        private ItemsChoiceType[] itemsElementNameField;

        private string nameField;

        private string physicalDirectoryField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VirtualApplication", typeof(VirtualDirectory))]
        [System.Xml.Serialization.XmlElementAttribute("VirtualDirectory", typeof(VirtualDirectory))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public VirtualDirectory[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName
        {
            get
            {
                return this.itemsElementNameField;
            }
            set
            {
                this.itemsElementNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("name")]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("physicalDirectory")]
        public string PhysicalDirectory
        {
            get
            {
                return this.physicalDirectoryField;
            }
            set
            {
                this.physicalDirectoryField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition", IncludeInSchema = false)]
    public enum ItemsChoiceType
    {

        /// <remarks/>
        VirtualApplication,

        /// <remarks/>
        VirtualDirectory,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition", IsNullable = false)]
    public partial class ServiceDefinition
    {

        private LoadBalancerProbe[] loadBalancerProbesField;

        private WebRole[] webRoleField;

        private WorkerRole[] workerRoleField;

        private OnlyAllowTrafficTo[] networkTrafficRulesField;

        private string nameField;

        private int upgradeDomainCountField;

        private SchemaVersion schemaVersionField;

        private TopologyChangeDiscovery topologyChangeDiscoveryField;

        public ServiceDefinition()
        {
            this.upgradeDomainCountField = 5;
            this.schemaVersionField = SchemaVersion.unspecified;
            this.topologyChangeDiscoveryField = TopologyChangeDiscovery.UpgradeDomainWalk;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public LoadBalancerProbe[] LoadBalancerProbes
        {
            get
            {
                return this.loadBalancerProbesField;
            }
            set
            {
                this.loadBalancerProbesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("WebRole")]
        public WebRole[] WebRole
        {
            get
            {
                return this.webRoleField;
            }
            set
            {
                this.webRoleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("WorkerRole")]
        public WorkerRole[] WorkerRole
        {
            get
            {
                return this.workerRoleField;
            }
            set
            {
                this.workerRoleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public OnlyAllowTrafficTo[] NetworkTrafficRules
        {
            get
            {
                return this.networkTrafficRulesField;
            }
            set
            {
                this.networkTrafficRulesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("name")]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("upgradeDomainCount")]
        [System.ComponentModel.DefaultValueAttribute(5)]
        public int UpgradeDomainCount
        {
            get
            {
                return this.upgradeDomainCountField;
            }
            set
            {
                this.upgradeDomainCountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("schemaVersion")]
        [System.ComponentModel.DefaultValueAttribute(SchemaVersion.unspecified)]
        public SchemaVersion SchemaVersion
        {
            get
            {
                return this.schemaVersionField;
            }
            set
            {
                this.schemaVersionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("topologyChangeDiscovery")]
        [System.ComponentModel.DefaultValueAttribute(TopologyChangeDiscovery.UpgradeDomainWalk)]
        public TopologyChangeDiscovery TopologyChangeDiscovery
        {
            get
            {
                return this.topologyChangeDiscoveryField;
            }
            set
            {
                this.topologyChangeDiscoveryField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition", IsNullable = true)]
    public partial class WebRole
    {

        private Import[] importsField;

        private Startup startupField;

        private LocalStore localStorageField;

        private LocalResources localResourcesField;

        private ConfigurationSetting[] configurationSettingsField;

        private WebRoleInputEndpoints inputEndpointsField;

        private WebRoleInternalEndpoint internalEndpointField;

        private Endpoints endpointsField;

        private Certificate[] certificatesField;

        private Sites sitesField;

        private WebRuntime runtimeField;

        private ContentElement[] contentsField;

        private string nameField;

        private bool enableNativeCodeExecutionField;

        private string vmsizeField;

        public WebRole()
        {
            this.enableNativeCodeExecutionField = true;
            this.vmsizeField = "Small";
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public Import[] Imports
        {
            get
            {
                return this.importsField;
            }
            set
            {
                this.importsField = value;
            }
        }

        /// <remarks/>
        public Startup Startup
        {
            get
            {
                return this.startupField;
            }
            set
            {
                this.startupField = value;
            }
        }

        /// <remarks/>
        public LocalStore LocalStorage
        {
            get
            {
                return this.localStorageField;
            }
            set
            {
                this.localStorageField = value;
            }
        }

        /// <remarks/>
        public LocalResources LocalResources
        {
            get
            {
                return this.localResourcesField;
            }
            set
            {
                this.localResourcesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Setting", IsNullable = false)]
        public ConfigurationSetting[] ConfigurationSettings
        {
            get
            {
                return this.configurationSettingsField;
            }
            set
            {
                this.configurationSettingsField = value;
            }
        }

        /// <remarks/>
        public WebRoleInputEndpoints InputEndpoints
        {
            get
            {
                return this.inputEndpointsField;
            }
            set
            {
                this.inputEndpointsField = value;
            }
        }

        /// <remarks/>
        public WebRoleInternalEndpoint InternalEndpoint
        {
            get
            {
                return this.internalEndpointField;
            }
            set
            {
                this.internalEndpointField = value;
            }
        }

        /// <remarks/>
        public Endpoints Endpoints
        {
            get
            {
                return this.endpointsField;
            }
            set
            {
                this.endpointsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public Certificate[] Certificates
        {
            get
            {
                return this.certificatesField;
            }
            set
            {
                this.certificatesField = value;
            }
        }

        /// <remarks/>
        public Sites Sites
        {
            get
            {
                return this.sitesField;
            }
            set
            {
                this.sitesField = value;
            }
        }

        /// <remarks/>
        public WebRuntime Runtime
        {
            get
            {
                return this.runtimeField;
            }
            set
            {
                this.runtimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Content", IsNullable = false)]
        public ContentElement[] Contents
        {
            get
            {
                return this.contentsField;
            }
            set
            {
                this.contentsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("name")]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("enableNativeCodeExecution")]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool EnableNativeCodeExecution
        {
            get
            {
                return this.enableNativeCodeExecutionField;
            }
            set
            {
                this.enableNativeCodeExecutionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("vmsize")]
        [System.ComponentModel.DefaultValueAttribute("Small")]
        public string Vmsize
        {
            get
            {
                return this.vmsizeField;
            }
            set
            {
                this.vmsizeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    public partial class WebRoleInputEndpoints
    {

        private WebRoleInputEndpointsInputEndpoint[] inputEndpointField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InputEndpoint")]
        public WebRoleInputEndpointsInputEndpoint[] InputEndpoint
        {
            get
            {
                return this.inputEndpointField;
            }
            set
            {
                this.inputEndpointField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    public partial class WebRoleInputEndpointsInputEndpoint : InputEndpoint
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    public partial class WebRoleInternalEndpoint : InternalEndpoint
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition", IsNullable = true)]
    public partial class WebRuntime : Runtime
    {

        private EntryPointElement entryPointField;

        /// <remarks/>
        public EntryPointElement EntryPoint
        {
            get
            {
                return this.entryPointField;
            }
            set
            {
                this.entryPointField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition", IsNullable = true)]
    public partial class EntryPointElement
    {

        private NetFxAssemblyEntryPointElement itemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NetFxEntryPoint")]
        public NetFxAssemblyEntryPointElement Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition", IsNullable = true)]
    public partial class NetFxAssemblyEntryPointElement
    {

        private string assemblyNameField;

        private string targetFrameworkVersionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("assemblyName")]
        public string AssemblyName
        {
            get
            {
                return this.assemblyNameField;
            }
            set
            {
                this.assemblyNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("targetFrameworkVersion")]
        public string TargetFrameworkVersion
        {
            get
            {
                return this.targetFrameworkVersionField;
            }
            set
            {
                this.targetFrameworkVersionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition", IsNullable = true)]
    public partial class ContentElement
    {

        private SourceDirectoryElement sourceDirectoryField;

        private string destinationField;

        /// <remarks/>
        public SourceDirectoryElement SourceDirectory
        {
            get
            {
                return this.sourceDirectoryField;
            }
            set
            {
                this.sourceDirectoryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("destination")]
        public string Destination
        {
            get
            {
                return this.destinationField;
            }
            set
            {
                this.destinationField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition", IsNullable = true)]
    public partial class SourceDirectoryElement
    {

        private string pathField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("path")]
        public string Path
        {
            get
            {
                return this.pathField;
            }
            set
            {
                this.pathField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition", IsNullable = true)]
    public partial class WorkerRole
    {

        private Import[] importsField;

        private Startup startupField;

        private LocalStore localStorageField;

        private LocalResources localResourcesField;

        private ConfigurationSetting[] configurationSettingsField;

        private Endpoints endpointsField;

        private Certificate[] certificatesField;

        private WorkerRuntime runtimeField;

        private ContentElement[] contentsField;

        private string nameField;

        private bool enableNativeCodeExecutionField;

        private string vmsizeField;

        public WorkerRole()
        {
            this.enableNativeCodeExecutionField = true;
            this.vmsizeField = "Small";
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public Import[] Imports
        {
            get
            {
                return this.importsField;
            }
            set
            {
                this.importsField = value;
            }
        }

        /// <remarks/>
        public Startup Startup
        {
            get
            {
                return this.startupField;
            }
            set
            {
                this.startupField = value;
            }
        }

        /// <remarks/>
        public LocalStore LocalStorage
        {
            get
            {
                return this.localStorageField;
            }
            set
            {
                this.localStorageField = value;
            }
        }

        /// <remarks/>
        public LocalResources LocalResources
        {
            get
            {
                return this.localResourcesField;
            }
            set
            {
                this.localResourcesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Setting", IsNullable = false)]
        public ConfigurationSetting[] ConfigurationSettings
        {
            get
            {
                return this.configurationSettingsField;
            }
            set
            {
                this.configurationSettingsField = value;
            }
        }

        /// <remarks/>
        public Endpoints Endpoints
        {
            get
            {
                return this.endpointsField;
            }
            set
            {
                this.endpointsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public Certificate[] Certificates
        {
            get
            {
                return this.certificatesField;
            }
            set
            {
                this.certificatesField = value;
            }
        }

        /// <remarks/>
        public WorkerRuntime Runtime
        {
            get
            {
                return this.runtimeField;
            }
            set
            {
                this.runtimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Content", IsNullable = false)]
        public ContentElement[] Contents
        {
            get
            {
                return this.contentsField;
            }
            set
            {
                this.contentsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("name")]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("enableNativeCodeExecution")]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool EnableNativeCodeExecution
        {
            get
            {
                return this.enableNativeCodeExecutionField;
            }
            set
            {
                this.enableNativeCodeExecutionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("vmsize")]
        [System.ComponentModel.DefaultValueAttribute("Small")]
        public string Vmsize
        {
            get
            {
                return this.vmsizeField;
            }
            set
            {
                this.vmsizeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition", IsNullable = true)]
    public partial class WorkerRuntime : Runtime
    {

        private WorkerEntryPointElement entryPointField;

        /// <remarks/>
        public WorkerEntryPointElement EntryPoint
        {
            get
            {
                return this.entryPointField;
            }
            set
            {
                this.entryPointField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition", IsNullable = true)]
    public partial class WorkerEntryPointElement
    {

        private object itemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NetFxEntryPoint", typeof(NetFxAssemblyEntryPointElement))]
        [System.Xml.Serialization.XmlElementAttribute("ProgramEntryPoint", typeof(ProgramEntryPointElement))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition", IsNullable = true)]
    public partial class ProgramEntryPointElement
    {

        private string commandLineField;

        private bool setReadyOnProcessStartField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("commandLine")]
        public string CommandLine
        {
            get
            {
                return this.commandLineField;
            }
            set
            {
                this.commandLineField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("setReadyOnProcessStart")]
        public bool SetReadyOnProcessStart
        {
            get
            {
                return this.setReadyOnProcessStartField;
            }
            set
            {
                this.setReadyOnProcessStartField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition", IsNullable = false)]
    public enum SchemaVersion
    {

        /// <remarks/>
        unspecified,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2015-04.2.6")]
        Item20150426,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition", IsNullable = false)]
    public enum TopologyChangeDiscovery
    {

        /// <remarks/>
        UpgradeDomainWalk,

        /// <remarks/>
        Blast,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition", IsNullable = true)]
    public partial class Certificates
    {

        private Certificate[] certificateField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Certificate")]
        public Certificate[] Certificate
        {
            get
            {
                return this.certificateField;
            }
            set
            {
                this.certificateField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition", IsNullable = true)]
    public partial class ConfigurationSettings
    {

        private ConfigurationSetting[] settingField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Setting")]
        public ConfigurationSetting[] Setting
        {
            get
            {
                return this.settingField;
            }
            set
            {
                this.settingField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition", IsNullable = true)]
    public partial class RdmaEndpointElement
    {

        private string nameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("name")]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition", IsNullable = true)]
    public partial class Bindings
    {

        private Binding[] bindingField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Binding")]
        public Binding[] Binding
        {
            get
            {
                return this.bindingField;
            }
            set
            {
                this.bindingField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition", IsNullable = true)]
    public partial class VirtualApplication : VirtualDirectory
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition", IsNullable = true)]
    public partial class NetworkTrafficRules
    {

        private OnlyAllowTrafficTo[] onlyAllowTrafficToField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OnlyAllowTrafficTo")]
        public OnlyAllowTrafficTo[] OnlyAllowTrafficTo
        {
            get
            {
                return this.onlyAllowTrafficToField;
            }
            set
            {
                this.onlyAllowTrafficToField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition", IsNullable = true)]
    public partial class Environment
    {

        private Variable[] variableField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Variable")]
        public Variable[] Variable
        {
            get
            {
                return this.variableField;
            }
            set
            {
                this.variableField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition", IsNullable = true)]
    public partial class LoadBalancerProbes
    {

        private LoadBalancerProbe[] loadBalancerProbeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LoadBalancerProbe")]
        public LoadBalancerProbe[] LoadBalancerProbe
        {
            get
            {
                return this.loadBalancerProbeField;
            }
            set
            {
                this.loadBalancerProbeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition", IsNullable = true)]
    public partial class Imports
    {

        private Import[] importField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Import")]
        public Import[] Import
        {
            get
            {
                return this.importField;
            }
            set
            {
                this.importField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition", IsNullable = true)]
    public partial class ContentsElement
    {

        private ContentElement[] contentField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Content")]
        public ContentElement[] Content
        {
            get
            {
                return this.contentField;
            }
            set
            {
                this.contentField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition", IsNullable = false)]
    public enum AnyPort
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("*")]
        Item,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition", IsNullable = false)]
    public enum BuiltinStoreName
    {

        /// <remarks/>
        My,

        /// <remarks/>
        Root,

        /// <remarks/>
        CA,

        /// <remarks/>
        Trust,

        /// <remarks/>
        Disallowed,

        /// <remarks/>
        TrustedPeople,

        /// <remarks/>
        TrustedPublisher,

        /// <remarks/>
        AuthRoot,

        /// <remarks/>
        AddressBook,
    }
}